### ISSUE TITLE
It will be good to add custom User-Agent like that of SEB.

### ISSUE THREAD

**Issue by busi-reddy-karnati** [SafeExamBrowser/Chrominimum#8]
We were trying to use webcam for   our application. We were keeping a check on certain browsers(not allowing any except seb). We  do that using custom user agent parameter that is provided in SEB settings. But using chrominimum gives a user agent that is particular and doesn't allow us to modify. That is causing a problem to block/allow the application.

**Comment by dbuechel** [comment]
Are you looking for an option to completely replace the user agent or add a suffix?

**Comment by busi-reddy-karnati** [comment]
Any of that would work. Because my application is checking for a particular string in that User-agent

**Comment by conceptwaves** [comment]
Hi Damian, 
We hit a blocker while trying to implement Webcam based Live proctoring in some Universities in Africa and India. 

When we switch to this Chrominimum for webcam support, we are no longer in a position to block out users who are trying to access the test via a Chrome browser (because user agent for both these browsers is the same).

We have very serious deadlines for conducting the exams this week. 

Is there any possibility of giving us a release which will let us choose chrominimum a custom User Agent ? 
Even if it is a constant string that is different from the one used by  chrome browser, it will suffice for now. 

Thanks in advance.

**Comment by dbuechel** [comment]
I will need to see whether I can implement this today, I think I should have the time to do so.

**Comment by busi-reddy-karnati** [comment]
Hi Damian,
It's so kind of you to consider our request. Could you tell me where to get the updated executable from?

**Comment by dbuechel** [comment]
Your feature request will be part of version 1.1. I'll see that I can finish it this week, if possible.

**Comment by dbuechel** [comment]
The feature is implemented, please refer to the latest release and its usage instructions for details on how to configure the suffix.
